---
- name: "Demonstrate connecting to switches"
  hosts: ios-switches
  gather_facts: yes
  tasks:
    - name: Run show ip interface brief
      ios_command:
        commands: show ip interface brief
      register: output
    - name: Print output
      debug:
        var: output
